vich_uploader:
    db_driver: orm

    mappings:
        employees:
            uri_prefix: /pictures/employees
            upload_destination: '%kernel.project_dir%/public/pictures/employees'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        ranks:
            uri_prefix: /images/ranks
            upload_destination: '%kernel.project_dir%/public/images/ranks'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
